module.exports = {
    "accommodation": {
        "id": 1717,
        "name": "GH Faridabad",
        "rating": 0,
        "phoneNumber": "9874561235",
        "location": "Faridabad",
        "sublocality": "Sector 30",
        "address": "121 ,Sector 30 ,Faridabad",
        "careTakerName": "Ramit",
        "contactNumber": "9874561235",
        "createdAt": null,
        "updatedAt": null,
        "capacity": 41,
        "imageUrl": "/images/accomodation/1717/DP/1960775206.jpg",
        "careTakerRating": null,
        "foodRating": null,
        "amenititesRating": null,
        "comments": null,
        "moreImages": [
            "/images/accomodation/1717/MORE/667249985.jpg"
        ],
        "distance": null,
        "type": "GUEST_HOUSE",
        "amenitiesList": [
            {
                "id": 3,
                "name": "Television"
            },
            {
                "id": 4,
                "name": "Gymanism"
            },
            {
                "id": 5,
                "name": "Coffee Maker"
            },
            {
                "id": 6,
                "name": "Induction Stove"
            }
        ],
        "latitude": 28.4425186,
        "longitude": 77.32239149999998,
        "rooms": [
            {
                "id": 4509,
                "name": "1",
                "createdAt": "30-05-2017 02:58:06",
                "updatedAt": "30-05-2017 02:58:06",
                "blocked": false,
                "reasonForBlocking": null,
                "blockedByFmno": null,
                "blockedByName": null,
                "blockedFrom": null,
                "blockedForChargeCodes": []
            },
            {
                "id": 4510,
                "name": "2",
                "createdAt": "30-05-2017 02:58:06",
                "updatedAt": "30-05-2017 02:58:06",
                "blocked": false,
                "reasonForBlocking": null,
                "blockedByFmno": null,
                "blockedByName": null,
                "blockedFrom": null,
                "blockedForChargeCodes": []
            },
            {
                "id": 4511,
                "name": "3",
                "createdAt": "30-05-2017 07:17:48",
                "updatedAt": "30-05-2017 07:17:48",
                "blocked": false,
                "reasonForBlocking": null,
                "blockedByFmno": null,
                "blockedByName": null,
                "blockedFrom": null,
                "blockedForChargeCodes": []
            },
            {
                "id": 4512,
                "name": "4",
                "createdAt": "30-05-2017 07:17:48",
                "updatedAt": "30-05-2017 07:17:48",
                "blocked": false,
                "reasonForBlocking": null,
                "blockedByFmno": null,
                "blockedByName": null,
                "blockedFrom": null,
                "blockedForChargeCodes": []
            },
            {
                "id": 4513,
                "name": "5",
                "createdAt": "30-05-2017 07:39:26",
                "updatedAt": "30-05-2017 07:39:26",
                "blocked": false,
                "reasonForBlocking": null,
                "blockedByFmno": null,
                "blockedByName": null,
                "blockedFrom": null,
                "blockedForChargeCodes": []
            },
            {
                "id": 4514,
                "name": "6",
                "createdAt": "30-05-2017 07:39:26",
                "updatedAt": "30-05-2017 07:39:26",
                "blocked": false,
                "reasonForBlocking": null,
                "blockedByFmno": null,
                "blockedByName": null,
                "blockedFrom": null,
                "blockedForChargeCodes": []
            },
            {
                "id": 4515,
                "name": "7",
                "createdAt": "30-05-2017 07:39:26",
                "updatedAt": "30-05-2017 07:39:26",
                "blocked": false,
                "reasonForBlocking": null,
                "blockedByFmno": null,
                "blockedByName": null,
                "blockedFrom": null,
                "blockedForChargeCodes": []
            },
            {
                "id": 4516,
                "name": "8",
                "createdAt": "30-05-2017 07:39:26",
                "updatedAt": "30-05-2017 07:39:26",
                "blocked": false,
                "reasonForBlocking": null,
                "blockedByFmno": null,
                "blockedByName": null,
                "blockedFrom": null,
                "blockedForChargeCodes": []
            },
            {
                "id": 4517,
                "name": "9",
                "createdAt": "30-05-2017 07:39:26",
                "updatedAt": "30-05-2017 07:39:26",
                "blocked": false,
                "reasonForBlocking": null,
                "blockedByFmno": null,
                "blockedByName": null,
                "blockedFrom": null,
                "blockedForChargeCodes": []
            },
            {
                "id": 4518,
                "name": "10",
                "createdAt": "30-05-2017 07:42:50",
                "updatedAt": "30-05-2017 07:42:50",
                "blocked": false,
                "reasonForBlocking": null,
                "blockedByFmno": null,
                "blockedByName": null,
                "blockedFrom": null,
                "blockedForChargeCodes": []
            },
            {
                "id": 4519,
                "name": "11",
                "createdAt": "30-05-2017 07:42:50",
                "updatedAt": "30-05-2017 07:42:50",
                "blocked": false,
                "reasonForBlocking": null,
                "blockedByFmno": null,
                "blockedByName": null,
                "blockedFrom": null,
                "blockedForChargeCodes": []
            },
            {
                "id": 4520,
                "name": "12",
                "createdAt": "30-05-2017 07:42:50",
                "updatedAt": "30-05-2017 07:42:50",
                "blocked": false,
                "reasonForBlocking": null,
                "blockedByFmno": null,
                "blockedByName": null,
                "blockedFrom": null,
                "blockedForChargeCodes": []
            },
            {
                "id": 4521,
                "name": "13",
                "createdAt": "30-05-2017 07:42:50",
                "updatedAt": "30-05-2017 07:42:50",
                "blocked": false,
                "reasonForBlocking": null,
                "blockedByFmno": null,
                "blockedByName": null,
                "blockedFrom": null,
                "blockedForChargeCodes": []
            },
            {
                "id": 4522,
                "name": "14",
                "createdAt": "30-05-2017 07:42:50",
                "updatedAt": "30-05-2017 07:42:50",
                "blocked": false,
                "reasonForBlocking": null,
                "blockedByFmno": null,
                "blockedByName": null,
                "blockedFrom": null,
                "blockedForChargeCodes": []
            },
            {
                "id": 4523,
                "name": "15",
                "createdAt": "30-05-2017 07:56:36",
                "updatedAt": "30-05-2017 07:56:36",
                "blocked": false,
                "reasonForBlocking": null,
                "blockedByFmno": null,
                "blockedByName": null,
                "blockedFrom": null,
                "blockedForChargeCodes": []
            },
            {
                "id": 4524,
                "name": "16",
                "createdAt": "30-05-2017 07:56:45",
                "updatedAt": "30-05-2017 07:56:45",
                "blocked": false,
                "reasonForBlocking": null,
                "blockedByFmno": null,
                "blockedByName": null,
                "blockedFrom": null,
                "blockedForChargeCodes": []
            },
            {
                "id": 4525,
                "name": "17",
                "createdAt": "30-05-2017 07:56:45",
                "updatedAt": "30-05-2017 07:56:45",
                "blocked": false,
                "reasonForBlocking": null,
                "blockedByFmno": null,
                "blockedByName": null,
                "blockedFrom": null,
                "blockedForChargeCodes": []
            },
            {
                "id": 4526,
                "name": "18",
                "createdAt": "30-05-2017 08:00:41",
                "updatedAt": "30-05-2017 08:00:41",
                "blocked": false,
                "reasonForBlocking": null,
                "blockedByFmno": null,
                "blockedByName": null,
                "blockedFrom": null,
                "blockedForChargeCodes": []
            },
            {
                "id": 4527,
                "name": "19",
                "createdAt": "30-05-2017 08:16:46",
                "updatedAt": "30-05-2017 08:16:46",
                "blocked": false,
                "reasonForBlocking": null,
                "blockedByFmno": null,
                "blockedByName": null,
                "blockedFrom": null,
                "blockedForChargeCodes": []
            },
            {
                "id": 4528,
                "name": "20",
                "createdAt": "30-05-2017 08:18:14",
                "updatedAt": "30-05-2017 08:18:14",
                "blocked": false,
                "reasonForBlocking": null,
                "blockedByFmno": null,
                "blockedByName": null,
                "blockedFrom": null,
                "blockedForChargeCodes": []
            },
            {
                "id": 4529,
                "name": "21",
                "createdAt": "30-05-2017 08:18:14",
                "updatedAt": "30-05-2017 08:18:14",
                "blocked": false,
                "reasonForBlocking": null,
                "blockedByFmno": null,
                "blockedByName": null,
                "blockedFrom": null,
                "blockedForChargeCodes": []
            },
            {
                "id": 4530,
                "name": "22",
                "createdAt": "30-05-2017 08:18:14",
                "updatedAt": "30-05-2017 08:18:14",
                "blocked": false,
                "reasonForBlocking": null,
                "blockedByFmno": null,
                "blockedByName": null,
                "blockedFrom": null,
                "blockedForChargeCodes": []
            },
            {
                "id": 4531,
                "name": "23",
                "createdAt": "30-05-2017 08:18:14",
                "updatedAt": "30-05-2017 08:18:14",
                "blocked": false,
                "reasonForBlocking": null,
                "blockedByFmno": null,
                "blockedByName": null,
                "blockedFrom": null,
                "blockedForChargeCodes": []
            },
            {
                "id": 4532,
                "name": "24",
                "createdAt": "30-05-2017 08:18:14",
                "updatedAt": "30-05-2017 08:18:14",
                "blocked": false,
                "reasonForBlocking": null,
                "blockedByFmno": null,
                "blockedByName": null,
                "blockedFrom": null,
                "blockedForChargeCodes": []
            },
            {
                "id": 4533,
                "name": "25",
                "createdAt": "30-05-2017 08:18:14",
                "updatedAt": "30-05-2017 08:18:14",
                "blocked": false,
                "reasonForBlocking": null,
                "blockedByFmno": null,
                "blockedByName": null,
                "blockedFrom": null,
                "blockedForChargeCodes": []
            },
            {
                "id": 4534,
                "name": "26",
                "createdAt": "30-05-2017 08:18:14",
                "updatedAt": "30-05-2017 08:18:14",
                "blocked": false,
                "reasonForBlocking": null,
                "blockedByFmno": null,
                "blockedByName": null,
                "blockedFrom": null,
                "blockedForChargeCodes": []
            },
            {
                "id": 4535,
                "name": "27",
                "createdAt": "30-05-2017 08:18:14",
                "updatedAt": "30-05-2017 08:18:14",
                "blocked": false,
                "reasonForBlocking": null,
                "blockedByFmno": null,
                "blockedByName": null,
                "blockedFrom": null,
                "blockedForChargeCodes": []
            },
            {
                "id": 4536,
                "name": "28",
                "createdAt": "30-05-2017 08:18:14",
                "updatedAt": "30-05-2017 08:18:14",
                "blocked": false,
                "reasonForBlocking": null,
                "blockedByFmno": null,
                "blockedByName": null,
                "blockedFrom": null,
                "blockedForChargeCodes": []
            },
            {
                "id": 4537,
                "name": "29",
                "createdAt": "30-05-2017 08:18:14",
                "updatedAt": "30-05-2017 08:18:14",
                "blocked": false,
                "reasonForBlocking": null,
                "blockedByFmno": null,
                "blockedByName": null,
                "blockedFrom": null,
                "blockedForChargeCodes": []
            },
            {
                "id": 4538,
                "name": "30",
                "createdAt": "30-05-2017 08:18:14",
                "updatedAt": "30-05-2017 08:18:14",
                "blocked": false,
                "reasonForBlocking": null,
                "blockedByFmno": null,
                "blockedByName": null,
                "blockedFrom": null,
                "blockedForChargeCodes": []
            },
            {
                "id": 4539,
                "name": "31",
                "createdAt": "30-05-2017 08:18:14",
                "updatedAt": "30-05-2017 08:18:14",
                "blocked": false,
                "reasonForBlocking": null,
                "blockedByFmno": null,
                "blockedByName": null,
                "blockedFrom": null,
                "blockedForChargeCodes": []
            },
            {
                "id": 4540,
                "name": "32",
                "createdAt": "30-05-2017 08:18:14",
                "updatedAt": "30-05-2017 08:18:14",
                "blocked": false,
                "reasonForBlocking": null,
                "blockedByFmno": null,
                "blockedByName": null,
                "blockedFrom": null,
                "blockedForChargeCodes": []
            },
            {
                "id": 4541,
                "name": "33",
                "createdAt": "30-05-2017 08:18:14",
                "updatedAt": "30-05-2017 08:18:14",
                "blocked": false,
                "reasonForBlocking": null,
                "blockedByFmno": null,
                "blockedByName": null,
                "blockedFrom": null,
                "blockedForChargeCodes": []
            },
            {
                "id": 4542,
                "name": "34",
                "createdAt": "30-05-2017 08:18:14",
                "updatedAt": "30-05-2017 08:18:14",
                "blocked": false,
                "reasonForBlocking": null,
                "blockedByFmno": null,
                "blockedByName": null,
                "blockedFrom": null,
                "blockedForChargeCodes": []
            },
            {
                "id": 4543,
                "name": "35",
                "createdAt": "30-05-2017 08:18:14",
                "updatedAt": "30-05-2017 08:18:14",
                "blocked": false,
                "reasonForBlocking": null,
                "blockedByFmno": null,
                "blockedByName": null,
                "blockedFrom": null,
                "blockedForChargeCodes": []
            },
            {
                "id": 4544,
                "name": "36",
                "createdAt": "30-05-2017 08:18:14",
                "updatedAt": "30-05-2017 08:18:14",
                "blocked": false,
                "reasonForBlocking": null,
                "blockedByFmno": null,
                "blockedByName": null,
                "blockedFrom": null,
                "blockedForChargeCodes": []
            },
            {
                "id": 4545,
                "name": "37",
                "createdAt": "30-05-2017 08:18:14",
                "updatedAt": "30-05-2017 08:18:14",
                "blocked": false,
                "reasonForBlocking": null,
                "blockedByFmno": null,
                "blockedByName": null,
                "blockedFrom": null,
                "blockedForChargeCodes": []
            },
            {
                "id": 4546,
                "name": "38",
                "createdAt": "30-05-2017 08:18:14",
                "updatedAt": "30-05-2017 08:18:14",
                "blocked": false,
                "reasonForBlocking": null,
                "blockedByFmno": null,
                "blockedByName": null,
                "blockedFrom": null,
                "blockedForChargeCodes": []
            },
            {
                "id": 4547,
                "name": "39",
                "createdAt": "30-05-2017 08:18:14",
                "updatedAt": "30-05-2017 08:18:14",
                "blocked": false,
                "reasonForBlocking": null,
                "blockedByFmno": null,
                "blockedByName": null,
                "blockedFrom": null,
                "blockedForChargeCodes": []
            },
            {
                "id": 4562,
                "name": "40",
                "createdAt": "30-05-2017 13:37:13",
                "updatedAt": "30-05-2017 13:37:13",
                "blocked": false,
                "reasonForBlocking": null,
                "blockedByFmno": null,
                "blockedByName": null,
                "blockedFrom": null,
                "blockedForChargeCodes": []
            },
            {
                "id": 4563,
                "name": "41",
                "createdAt": "30-05-2017 13:38:26",
                "updatedAt": "30-05-2017 13:38:26",
                "blocked": false,
                "reasonForBlocking": null,
                "blockedByFmno": null,
                "blockedByName": null,
                "blockedFrom": null,
                "blockedForChargeCodes": []
            }
        ],
        "videoConference": false
    },
    "bookings": [
        {
            "id": 6743,
            "chargeCode": "PLM524",
            "mobilePhone": "7894563214",
            "avatar": null,
            "type": "GUEST_HOUSE",
            "careTakerRating": null,
            "foodRating": null,
            "amenititesRating": null,
            "editRef": null,
            "guestComments": null,
            "adminComments": null,
            "isParentBooking": false,
            "guestType": "NON_EMPLOYEE",
            "excludeFriday": false,
            "excludeSaturday": true,
            "excludeSunday": true,
            "checkinDate": "30-05-2017",
            "checkoutDate": "07-06-2017",
            "checkinTime": "18:00",
            "checkoutTime": "12:00",
            "status": "CONFIRMED",
            "location": "Faridabad",
            "address": "Faridabad, Haryana, India",
            "lastUpdatedByFmno": "130144",
            "lastUpdatedByName": "Aditya Thangeda",
            "createdAt": 1496124152000,
            "updatedAt": 1496124191000,
            "additionalRequestText": "",
            "requestACareTakerText": "",
            "allotedAccommodation": {
                "id": 1717,
                "name": "GH Faridabad",
                "rating": 0,
                "phoneNumber": "9874561235",
                "location": "Faridabad",
                "sublocality": "Sector 30",
                "address": "121 ,Sector 30 ,Faridabad",
                "careTakerName": "Ramit",
                "contactNumber": "9874561235",
                "createdAt": null,
                "updatedAt": null,
                "capacity": 41,
                "imageUrl": "/images/accomodation/1717/DP/1960775206.jpg",
                "careTakerRating": null,
                "foodRating": null,
                "amenititesRating": null,
                "comments": null,
                "moreImages": [
                    "/images/accomodation/1717/MORE/667249985.jpg"
                ],
                "distance": null,
                "type": "GUEST_HOUSE",
                "amenitiesList": [
                    {
                        "id": 3,
                        "name": "Television"
                    },
                    {
                        "id": 4,
                        "name": "Gymanism"
                    },
                    {
                        "id": 5,
                        "name": "Coffee Maker"
                    },
                    {
                        "id": 6,
                        "name": "Induction Stove"
                    }
                ],
                "latitude": 28.4425186,
                "longitude": 77.32239149999998,
                "rooms": [
                    {
                        "id": 4509,
                        "name": "1",
                        "createdAt": "30-05-2017 02:58:06",
                        "updatedAt": "30-05-2017 02:58:06",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4510,
                        "name": "2",
                        "createdAt": "30-05-2017 02:58:06",
                        "updatedAt": "30-05-2017 02:58:06",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4511,
                        "name": "3",
                        "createdAt": "30-05-2017 07:17:48",
                        "updatedAt": "30-05-2017 07:17:48",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4512,
                        "name": "4",
                        "createdAt": "30-05-2017 07:17:48",
                        "updatedAt": "30-05-2017 07:17:48",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4513,
                        "name": "5",
                        "createdAt": "30-05-2017 07:39:26",
                        "updatedAt": "30-05-2017 07:39:26",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4514,
                        "name": "6",
                        "createdAt": "30-05-2017 07:39:26",
                        "updatedAt": "30-05-2017 07:39:26",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4515,
                        "name": "7",
                        "createdAt": "30-05-2017 07:39:26",
                        "updatedAt": "30-05-2017 07:39:26",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4516,
                        "name": "8",
                        "createdAt": "30-05-2017 07:39:26",
                        "updatedAt": "30-05-2017 07:39:26",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4517,
                        "name": "9",
                        "createdAt": "30-05-2017 07:39:26",
                        "updatedAt": "30-05-2017 07:39:26",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4518,
                        "name": "10",
                        "createdAt": "30-05-2017 07:42:50",
                        "updatedAt": "30-05-2017 07:42:50",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4519,
                        "name": "11",
                        "createdAt": "30-05-2017 07:42:50",
                        "updatedAt": "30-05-2017 07:42:50",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4520,
                        "name": "12",
                        "createdAt": "30-05-2017 07:42:50",
                        "updatedAt": "30-05-2017 07:42:50",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4521,
                        "name": "13",
                        "createdAt": "30-05-2017 07:42:50",
                        "updatedAt": "30-05-2017 07:42:50",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4522,
                        "name": "14",
                        "createdAt": "30-05-2017 07:42:50",
                        "updatedAt": "30-05-2017 07:42:50",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4523,
                        "name": "15",
                        "createdAt": "30-05-2017 07:56:36",
                        "updatedAt": "30-05-2017 07:56:36",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4524,
                        "name": "16",
                        "createdAt": "30-05-2017 07:56:45",
                        "updatedAt": "30-05-2017 07:56:45",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4525,
                        "name": "17",
                        "createdAt": "30-05-2017 07:56:45",
                        "updatedAt": "30-05-2017 07:56:45",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4526,
                        "name": "18",
                        "createdAt": "30-05-2017 08:00:41",
                        "updatedAt": "30-05-2017 08:00:41",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4527,
                        "name": "19",
                        "createdAt": "30-05-2017 08:16:46",
                        "updatedAt": "30-05-2017 08:16:46",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4528,
                        "name": "20",
                        "createdAt": "30-05-2017 08:18:14",
                        "updatedAt": "30-05-2017 08:18:14",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4529,
                        "name": "21",
                        "createdAt": "30-05-2017 08:18:14",
                        "updatedAt": "30-05-2017 08:18:14",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4530,
                        "name": "22",
                        "createdAt": "30-05-2017 08:18:14",
                        "updatedAt": "30-05-2017 08:18:14",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4531,
                        "name": "23",
                        "createdAt": "30-05-2017 08:18:14",
                        "updatedAt": "30-05-2017 08:18:14",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4532,
                        "name": "24",
                        "createdAt": "30-05-2017 08:18:14",
                        "updatedAt": "30-05-2017 08:18:14",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4533,
                        "name": "25",
                        "createdAt": "30-05-2017 08:18:14",
                        "updatedAt": "30-05-2017 08:18:14",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4534,
                        "name": "26",
                        "createdAt": "30-05-2017 08:18:14",
                        "updatedAt": "30-05-2017 08:18:14",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4535,
                        "name": "27",
                        "createdAt": "30-05-2017 08:18:14",
                        "updatedAt": "30-05-2017 08:18:14",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4536,
                        "name": "28",
                        "createdAt": "30-05-2017 08:18:14",
                        "updatedAt": "30-05-2017 08:18:14",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4537,
                        "name": "29",
                        "createdAt": "30-05-2017 08:18:14",
                        "updatedAt": "30-05-2017 08:18:14",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4538,
                        "name": "30",
                        "createdAt": "30-05-2017 08:18:14",
                        "updatedAt": "30-05-2017 08:18:14",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4539,
                        "name": "31",
                        "createdAt": "30-05-2017 08:18:14",
                        "updatedAt": "30-05-2017 08:18:14",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4540,
                        "name": "32",
                        "createdAt": "30-05-2017 08:18:14",
                        "updatedAt": "30-05-2017 08:18:14",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4541,
                        "name": "33",
                        "createdAt": "30-05-2017 08:18:14",
                        "updatedAt": "30-05-2017 08:18:14",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4542,
                        "name": "34",
                        "createdAt": "30-05-2017 08:18:14",
                        "updatedAt": "30-05-2017 08:18:14",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4543,
                        "name": "35",
                        "createdAt": "30-05-2017 08:18:14",
                        "updatedAt": "30-05-2017 08:18:14",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4544,
                        "name": "36",
                        "createdAt": "30-05-2017 08:18:14",
                        "updatedAt": "30-05-2017 08:18:14",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4545,
                        "name": "37",
                        "createdAt": "30-05-2017 08:18:14",
                        "updatedAt": "30-05-2017 08:18:14",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4546,
                        "name": "38",
                        "createdAt": "30-05-2017 08:18:14",
                        "updatedAt": "30-05-2017 08:18:14",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4547,
                        "name": "39",
                        "createdAt": "30-05-2017 08:18:14",
                        "updatedAt": "30-05-2017 08:18:14",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4562,
                        "name": "40",
                        "createdAt": "30-05-2017 13:37:13",
                        "updatedAt": "30-05-2017 13:37:13",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4563,
                        "name": "41",
                        "createdAt": "30-05-2017 13:38:26",
                        "updatedAt": "30-05-2017 13:38:26",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    }
                ],
                "videoConference": false
            },
            "allocatedRoom": {
                "id": 4509,
                "name": "5",
                "createdAt": "30-05-2017 02:58:06",
                "updatedAt": "30-05-2017 02:58:06",
                "blocked": false,
                "reasonForBlocking": null,
                "blockedByFmno": null,
                "blockedByName": null,
                "blockedFrom": null,
                "blockedForChargeCodes": []
            },
            "noOfDaysBookingRequired": 4,
            "latitude": 28.4089123,
            "longitude": 77.31778940000004,
            "requesterFmnoId": "130144",
            "requesterName": "Aditya Thangeda",
            "requesterEmail": "Aditya_Thangeda@mckinsey.com",
            "bookingTimeEnded": false,
            "videoConference": false,
            "editRequest": false,
            "bookingTimeStarted": true,
            "deAllocationRequired": true,
            "guestName": "Lionel Messi",
            "guestEmail": "messi@alien.com",
            "guestFmno": ""
        },
        {
            "id": 6750,
            "chargeCode": "PLM524",
            "mobilePhone": "78845454545",
            "avatar": null,
            "type": "GUEST_HOUSE",
            "careTakerRating": null,
            "foodRating": null,
            "amenititesRating": null,
            "editRef": null,
            "guestComments": null,
            "adminComments": null,
            "isParentBooking": false,
            "guestType": "NON_EMPLOYEE",
            "excludeFriday": false,
            "excludeSaturday": true,
            "excludeSunday": true,
            "checkinDate": "30-05-2017",
            "checkoutDate": "03-06-2017",
            "checkinTime": "18:00",
            "checkoutTime": "12:00",
            "status": "CONFIRMED",
            "location": "Faridabad",
            "address": "Faridabad, Haryana, India",
            "lastUpdatedByFmno": "130144",
            "lastUpdatedByName": "Aditya Thangeda",
            "createdAt": 1496124294000,
            "updatedAt": 1496124303000,
            "additionalRequestText": "",
            "requestACareTakerText": "",
            "allotedAccommodation": {
                "id": 1717,
                "name": "GH Faridabad",
                "rating": 0,
                "phoneNumber": "9874561235",
                "location": "Faridabad",
                "sublocality": "Sector 30",
                "address": "121 ,Sector 30 ,Faridabad",
                "careTakerName": "Ramit",
                "contactNumber": "9874561235",
                "createdAt": null,
                "updatedAt": null,
                "capacity": 41,
                "imageUrl": "/images/accomodation/1717/DP/1960775206.jpg",
                "careTakerRating": null,
                "foodRating": null,
                "amenititesRating": null,
                "comments": null,
                "moreImages": [
                    "/images/accomodation/1717/MORE/667249985.jpg"
                ],
                "distance": null,
                "type": "GUEST_HOUSE",
                "amenitiesList": [
                    {
                        "id": 3,
                        "name": "Television"
                    },
                    {
                        "id": 4,
                        "name": "Gymanism"
                    },
                    {
                        "id": 5,
                        "name": "Coffee Maker"
                    },
                    {
                        "id": 6,
                        "name": "Induction Stove"
                    }
                ],
                "latitude": 28.4425186,
                "longitude": 77.32239149999998,
                "rooms": [
                    {
                        "id": 4509,
                        "name": "1",
                        "createdAt": "30-05-2017 02:58:06",
                        "updatedAt": "30-05-2017 02:58:06",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4510,
                        "name": "2",
                        "createdAt": "30-05-2017 02:58:06",
                        "updatedAt": "30-05-2017 02:58:06",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4511,
                        "name": "3",
                        "createdAt": "30-05-2017 07:17:48",
                        "updatedAt": "30-05-2017 07:17:48",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4512,
                        "name": "4",
                        "createdAt": "30-05-2017 07:17:48",
                        "updatedAt": "30-05-2017 07:17:48",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4513,
                        "name": "5",
                        "createdAt": "30-05-2017 07:39:26",
                        "updatedAt": "30-05-2017 07:39:26",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4514,
                        "name": "6",
                        "createdAt": "30-05-2017 07:39:26",
                        "updatedAt": "30-05-2017 07:39:26",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4515,
                        "name": "7",
                        "createdAt": "30-05-2017 07:39:26",
                        "updatedAt": "30-05-2017 07:39:26",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4516,
                        "name": "8",
                        "createdAt": "30-05-2017 07:39:26",
                        "updatedAt": "30-05-2017 07:39:26",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4517,
                        "name": "9",
                        "createdAt": "30-05-2017 07:39:26",
                        "updatedAt": "30-05-2017 07:39:26",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4518,
                        "name": "10",
                        "createdAt": "30-05-2017 07:42:50",
                        "updatedAt": "30-05-2017 07:42:50",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4519,
                        "name": "11",
                        "createdAt": "30-05-2017 07:42:50",
                        "updatedAt": "30-05-2017 07:42:50",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4520,
                        "name": "12",
                        "createdAt": "30-05-2017 07:42:50",
                        "updatedAt": "30-05-2017 07:42:50",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4521,
                        "name": "13",
                        "createdAt": "30-05-2017 07:42:50",
                        "updatedAt": "30-05-2017 07:42:50",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4522,
                        "name": "14",
                        "createdAt": "30-05-2017 07:42:50",
                        "updatedAt": "30-05-2017 07:42:50",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4523,
                        "name": "15",
                        "createdAt": "30-05-2017 07:56:36",
                        "updatedAt": "30-05-2017 07:56:36",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4524,
                        "name": "16",
                        "createdAt": "30-05-2017 07:56:45",
                        "updatedAt": "30-05-2017 07:56:45",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4525,
                        "name": "17",
                        "createdAt": "30-05-2017 07:56:45",
                        "updatedAt": "30-05-2017 07:56:45",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4526,
                        "name": "18",
                        "createdAt": "30-05-2017 08:00:41",
                        "updatedAt": "30-05-2017 08:00:41",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4527,
                        "name": "19",
                        "createdAt": "30-05-2017 08:16:46",
                        "updatedAt": "30-05-2017 08:16:46",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4528,
                        "name": "20",
                        "createdAt": "30-05-2017 08:18:14",
                        "updatedAt": "30-05-2017 08:18:14",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4529,
                        "name": "21",
                        "createdAt": "30-05-2017 08:18:14",
                        "updatedAt": "30-05-2017 08:18:14",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4530,
                        "name": "22",
                        "createdAt": "30-05-2017 08:18:14",
                        "updatedAt": "30-05-2017 08:18:14",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4531,
                        "name": "23",
                        "createdAt": "30-05-2017 08:18:14",
                        "updatedAt": "30-05-2017 08:18:14",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4532,
                        "name": "24",
                        "createdAt": "30-05-2017 08:18:14",
                        "updatedAt": "30-05-2017 08:18:14",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4533,
                        "name": "25",
                        "createdAt": "30-05-2017 08:18:14",
                        "updatedAt": "30-05-2017 08:18:14",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4534,
                        "name": "26",
                        "createdAt": "30-05-2017 08:18:14",
                        "updatedAt": "30-05-2017 08:18:14",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4535,
                        "name": "27",
                        "createdAt": "30-05-2017 08:18:14",
                        "updatedAt": "30-05-2017 08:18:14",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4536,
                        "name": "28",
                        "createdAt": "30-05-2017 08:18:14",
                        "updatedAt": "30-05-2017 08:18:14",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4537,
                        "name": "29",
                        "createdAt": "30-05-2017 08:18:14",
                        "updatedAt": "30-05-2017 08:18:14",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4538,
                        "name": "30",
                        "createdAt": "30-05-2017 08:18:14",
                        "updatedAt": "30-05-2017 08:18:14",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4539,
                        "name": "31",
                        "createdAt": "30-05-2017 08:18:14",
                        "updatedAt": "30-05-2017 08:18:14",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4540,
                        "name": "32",
                        "createdAt": "30-05-2017 08:18:14",
                        "updatedAt": "30-05-2017 08:18:14",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4541,
                        "name": "33",
                        "createdAt": "30-05-2017 08:18:14",
                        "updatedAt": "30-05-2017 08:18:14",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4542,
                        "name": "34",
                        "createdAt": "30-05-2017 08:18:14",
                        "updatedAt": "30-05-2017 08:18:14",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4543,
                        "name": "35",
                        "createdAt": "30-05-2017 08:18:14",
                        "updatedAt": "30-05-2017 08:18:14",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4544,
                        "name": "36",
                        "createdAt": "30-05-2017 08:18:14",
                        "updatedAt": "30-05-2017 08:18:14",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4545,
                        "name": "37",
                        "createdAt": "30-05-2017 08:18:14",
                        "updatedAt": "30-05-2017 08:18:14",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4546,
                        "name": "38",
                        "createdAt": "30-05-2017 08:18:14",
                        "updatedAt": "30-05-2017 08:18:14",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4547,
                        "name": "39",
                        "createdAt": "30-05-2017 08:18:14",
                        "updatedAt": "30-05-2017 08:18:14",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4562,
                        "name": "40",
                        "createdAt": "30-05-2017 13:37:13",
                        "updatedAt": "30-05-2017 13:37:13",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    },
                    {
                        "id": 4563,
                        "name": "41",
                        "createdAt": "30-05-2017 13:38:26",
                        "updatedAt": "30-05-2017 13:38:26",
                        "blocked": false,
                        "reasonForBlocking": null,
                        "blockedByFmno": null,
                        "blockedByName": null,
                        "blockedFrom": null,
                        "blockedForChargeCodes": []
                    }
                ],
                "videoConference": false
            },
            "allocatedRoom": {
                "id": 4510,
                "name": "10",
                "createdAt": "30-05-2017 02:58:06",
                "updatedAt": "30-05-2017 02:58:06",
                "blocked": false,
                "reasonForBlocking": null,
                "blockedByFmno": null,
                "blockedByName": null,
                "blockedFrom": null,
                "blockedForChargeCodes": []
            },
            "noOfDaysBookingRequired": 4,
            "latitude": 28.4089123,
            "longitude": 77.31778940000004,
            "requesterFmnoId": "130144",
            "requesterName": "Aditya Thangeda",
            "requesterEmail": "Aditya_Thangeda@mckinsey.com",
            "bookingTimeEnded": false,
            "videoConference": false,
            "editRequest": false,
            "bookingTimeStarted": true,
            "deAllocationRequired": true,
            "guestName": "Andres Iniesta",
            "guestEmail": "andres@idol.com",
            "guestFmno": ""
        }
    ]
}